env:
  global:
  - GH_REF: github.com/nhz-io/nhz-sink.git
  - secure: QC0T5gCXni4kmS4yKnIWxAeguwA/7q1LlvEQ1Dp97BUu9ewUN+5gc5GOfmiaHinDz0NRPp2azRgVJ7stWbghqSnw3b2FEUpAcG7QB8POSMj1TidIY1VrKlwPAUrnbZXS4XPQgwaWGvCbebCPOiay8fEyezWDqdTt2p4qaNlJjV9vQf4nHcKkroGfAMFigSnMaEFXrL8l1Fx+0mo0/+1KSmI1FgC/KnETZn2GpGrtXZBJAo2O98Uu7NEmSXtPSA9tm7vChqylbYx14oJaM25r4lBq+mn0LuqTrfP2BkbEkoPyg5LjUr4+Y4YHbrUV08+EwJObCOXKuMiGQ4QofJrYkt1Vgi9GxJRq1Wd+Wa3Z25BjY00pK+6GitUrXzwx6aVw9XNkckZLq5rCCxJqydEPYvs6peHkoFk8rBUlCUkSnHHOFxia5ITwtUGkfL70YFavnD2NqhMpb/k7LeO8sVCnvQvV+VVDok6N63bQBo8AN0fMWdKPF8tolVAyB+g+FBvlOsgqzH3txQthagF4O/b7c1YgQJ1iF/k3APc2Shr5NDqUNdWowBoem61pGDUqzpG/gpe/3cRka7hlw8pFgT8CbCGinS+jSYd15aNi8HjYaxvI0VptFdPdKSwBjuZt10niJ0FO/hcCMnvGv8UwwblXZeyw/oZyp8p8m6rGd5RgAKY=
language: node_js
node_js:
- '4.2'
script: npm run-script travis
deploy:
  provider: npm
  email: dev@nhz.io
  api_key:
    secure: yseOyLrqBmeLsHI9jUyRBgpQ1RL1eimqgvRDI4xj5Awlz1FfETcGbyjL1o4OPob5us+5rf3SGvu/CPJpn7rhnHYpm382N+cxhkHnFBMMAezcYMEa6qa7LkTvZnQLPovxslEVgMs43RmivNfEaigsQN3rrJ1jgL59WwxWghUw383vUJN2tI6pDx/FPqhiVBDmq3PCag5H+nl+mgMDEacxAvnw4S/yGRNZLdWWh965mMZHHaHHO/9YzLBVdrP/gbKV40IJsuA5bhYJGxBgvKUIXlykv5VA75ni2qCdhVz6hyfCEt9NoAUKxrLBCOorjeM1a/BKjmQU3UMnpx62QJy+HrUFETunL5G1b71rBFX7uEPQ38mtNQr7gOrGsT/7yu2T7uFFNtgRiwF7lQCDYPvLG8gHGXRd1MQgvQIIUblI2yUluirrtrDJuckEvarOecE8zUMZtiEZ5qkc4ygvhfVOm2L4mlc8tqZSDVwsUaK3zSvVha/Toy0p4jV+s6P3IPUUjP7IyXZi748LarV9/73bP1wxkFJx9ywMGG8yCJ8QZURwWsfYSuQaDIYbriL5MhSsHnOcOLoPpa5We3XPYSlqR3zDKtdn0GcUvMPcJ6avOP4jQ5RN+tLcPjaqprw6Oju3wKa9RGqtbqEF+JbbMrJGs22ZFxVp5ot4DabtfCbCXy8=
  on:
    repo: nhz-io/nhz-sink
    branch: master
after_deploy:
- bash ./gh-pages.sh
